name = "TGW2D"
uuid = "90dab5c1-3a58-4898-9fd8-88b0ac8de5d4"
desc = "Topogical Gift Wrapping 2D"
authors = ["matteomaraziti<mat.maraziti@stud.uniroma3.it>, FTocci<fed.tocci@stud.uniroma3.it>, giacomoscordino<gia.scordino1@stud.uniroma3.it>"]
version = "0.1.0"
license = "MIT"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebraicRepresentation = "95167b0c-186a-594b-a231-52369c6de044"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
[compat]
IntervalTrees = "^1.0.0"
NearestNeighbors = "^0.4.3"
julia = "1.6.0"
LinearAlgebraicRepresentation = "^1.0.0"
DataStructures = "^0.18.13"
